name: XYZ

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu al
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Gerekli kütüphane
        run: pip install httpx

      - name: Scripti çalıştır
        run: python xyz.py

      - name: Dosya kontrol
        run: ls -la

      - name: Repo'ya commit et (sadece değişiklik varsa)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add xyz.m3u
          if ! git diff --cached --quiet; then
            git commit -m "Update xyz.m3u"
            git push
          else
            echo "Değişiklik yok"
          fi
